version: '3.8'

services:
  vodc-chatbot:
    build: .
    container_name: vodc-chatbot
    ports:
      - "8085:8085"
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8085
      - FLASK_DEBUG=false
      - OLLAMA_URL=http://host.docker.internal:11434
      - CORS_ORIGINS=*
    volumes:
      - ./knowledge_base:/app/knowledge_base
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - vodc-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8085/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Опционально: nginx для проксирования
  nginx:
    image: nginx:alpine
    container_name: vodc-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - vodc-chatbot
    restart: unless-stopped
    networks:
      - vodc-network

networks:
  vodc-network:
    driver: bridge

volumes:
  vodc-logs:
    driver: local